version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: query_management_mysql
    environment:
      MYSQL_DATABASE: loginapp
      MYSQL_USER: loginuser
      MYSQL_PASSWORD: loginpass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
