[phases.setup]
nixPkgs = ['openjdk17']

[phases.build]
cmds = ['cd loginapp && ./mvnw clean package -DskipTests']

[phases.start]
cmd = 'cd loginapp && java -jar target/*.jar'

[variables]
RAILWAY_SERVICE_ROOT = 'loginapp'
